### ISSUE TITLE
UI fix required. With a suitable color combination added. Cards are responsive.

### ISSUE THREAD

**Issue by RiturajGupta21** [CodingWizardITER/GearUp#1]
Special attention required for "about the event" and nav menu for smaller devices

**Comment by vishal5251** [comment]
Assign this one to me. Add discussion channel to this repo. Thanks!

**Comment by RiturajGupta21** [comment]
Okay

**Comment by Rajni2002** [comment]
@RiturajGupta21  I'm Working on this. Tonight I'll make a PR. 👍
